//
// Generated file, do not edit! Created by opp_msgc 4.3 from sensedsignal.msg.
//

#ifndef _SENSEDSIGNAL_M_H_
#define _SENSEDSIGNAL_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>sensedsignal.msg</tt> by opp_msgc.
 * <pre>
 * message SensedSignal {
 *     int tarId; 
 *     string signal; 
 *     double distance; 
 * }
 * </pre>
 */
class SensedSignal : public ::cMessage
{
  protected:
    int tarId_var;
    opp_string signal_var;
    double distance_var;

  private:
    void copy(const SensedSignal& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SensedSignal&);

  public:
    SensedSignal(const char *name=NULL, int kind=0);
    SensedSignal(const SensedSignal& other);
    virtual ~SensedSignal();
    SensedSignal& operator=(const SensedSignal& other);
    virtual SensedSignal *dup() const {return new SensedSignal(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getTarId() const;
    virtual void setTarId(int tarId);
    virtual const char * getSignal() const;
    virtual void setSignal(const char * signal);
    virtual double getDistance() const;
    virtual void setDistance(double distance);
};

inline void doPacking(cCommBuffer *b, SensedSignal& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SensedSignal& obj) {obj.parsimUnpack(b);}


#endif // _SENSEDSIGNAL_M_H_
